B4_setAllSeen_#148
SzFMV2020-Osz/AutomatedCar-B pull request #170
Opened 2020-11-02 21:46 UTC by sarilevente

Forever béna leszek ennek a megfelelő linkelésében.
https://github.com/SzFMV2020-Osz/AutomatedCar-B/issues/148

2020-11-03 07:46 UTC, zsofiath requested changes
Írnál hozzá még tesztet légyszi?

2020-11-03 07:46 UTC, zsofiath commented on src/AutomatedCar/Models/Radar.cs
> +            foreach (var noticeObj in noticedObjects)
var helyett inkább a valós class-t használjuk.

2020-11-04 16:18 UTC, zsofiath approved these changes

2020-11-05 07:09 UTC, pintergreg approved these changes

2020-11-05 07:10 UTC, merged