B4_isInNoticedObjects_#149
SzFMV2020-Osz/AutomatedCar-B pull request #175
Opened 2020-11-04 15:12 UTC by sarilevente

https://github.com/SzFMV2020-Osz/AutomatedCar-B/issues/149

2020-11-04 15:51 UTC, pintergreg submitted a review, later dismissed

2020-11-04 18:18 UTC, zsofiath requested changes
Légyszi írj tesztet több esetre! Ne a többi csapaton múljon, hogy le tudjuk tesztelni a munkánkat.

2020-11-04 18:18 UTC, zsofiath commented on src/AutomatedCar/Models/Radar.cs
> +                if (ReferenceEquals(noticedObject, paramWorldObject))
ezeknek sose lesz azonos a referenciája. A NoticedObject-nek van egy worldObject paramétere. Arra kell vizsgálni.

2020-11-15 09:41 UTC, zsofiath submitted a review, later dismissed

2020-11-15 09:44 UTC, zsofiath approved these changes

2020-11-16 09:44 UTC, pintergreg approved these changes

2020-11-16 09:47 UTC, merged