On break gas equals zero
SzFMV2020-Osz/AutomatedCar-B pull request #211
Opened 2020-11-30 15:20 UTC by TravnikGergely

PowerTrain javaslatára: ha fékpedál le van nyomva akkor a gázpedál értéke 0

2020-11-30 15:23 UTC, TravnikGergely commented
+véletlen az is benne van hogy 

- a tábla ki legyen jelezve ha volt utólag látott tábla
- Dashboardon megjelenik a tolatóradar panele

2020-11-30 19:00 UTC, balintszvoboda approved these changes

2020-12-01 06:46 UTC, pintergreg commented on src/AutomatedCar/Views/Converters/LastSeenSignConverter.cs
> +                return new Bitmap(@"..\..\..\\Assets\no_sign.png");
Ez a rész problémás ha nem Windows-on vagy, talán ott sem mindig jó.
Ilyen módon az assembly-ből legyen kiszedve:

```csharp
new Bitmap(Assembly.GetExecutingAssembly()
                        .GetManifestResourceStream($"AutomatedCar.Assets.WorldObjects.{filename}.png")))
```

2020-12-01 06:50 UTC, pintergreg requested changes
A fájlbetöltés nem platformfüggetlen.

@TravnikGergely Tegnap mondtad, hogy szétszeded a PR-t. Ez nem feltétlen szükséges, mert gondolom a többi módosítás is kell előbb utóbb (bár valóban elegánsabb ha funkciónként külön PR van).

2020-12-02 08:55 UTC, merged